name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
      
    - name: Install dependencies
      run: npm ci
  
    - name: Run linter
      uses: Adzz/jest_test_action@v1.0.0
      with:
        command: prettier:format && lint:check-errors

    - name: Run Cypress Tests
      uses: Adzz/jest_test_action@v1.0.0
      with:
        command: cy:run:chrome && cy:run:firefox
